POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Postman is a good tool for testing a REST API",
    "important":true
}

###

GET http://localhost:3002/api/persons

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name":"Ada Lovelace",
    "number": "123445653465235"
}

###
GET http://localhost:3002/api/persons/6388c41b4e9c4fd94eb22655

###
PUT http://localhost:3002/api/persons/6388c41b4e9c4fd94eb22655
Content-Type: application/json

{
    "name":"Ada Lovelace",
    "number": "12"
}

###
DELETE http://localhost:3002/api/persons/6388c41b4e9c4fd94eb22655